---
production:
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>
      options:
        skip_version_check: true
        safe: true
development:
  sessions:
    default:
      database: trafficyago_development
      hosts:
        - localhost:49153
test:
  sessions:
    default:
      database: trafficyago_test
      hosts:
        - localhost:49153
